backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "firms"
    label: "Підприємства"
    folder: "src/data/firms"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Назва", name: "title", widget: "string" }
      - { label: "Слоган", name: "slogan", widget: "string" }
      - { label: "Опис", name: "description", widget: "text" }
      - { label: "Години", name: "hours", widget: "string" }
      - { label: "Адреса", name: "address", widget: "string" }
      - { label: "Телефон", name: "phone", widget: "string", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "Фото", name: "photo", widget: "image", required: false }
